CREATE TABLE IF NOT EXISTS realisation_projects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug VARCHAR(140) NOT NULL,
  title VARCHAR(220) NOT NULL,
  tag ENUM('Web', 'IT', 'Formation', 'Business') NOT NULL DEFAULT 'Business',
  client_name VARCHAR(180) NOT NULL,
  sector VARCHAR(180) NOT NULL,
  context_text TEXT NOT NULL,
  challenge_text TEXT NOT NULL,
  solution_text TEXT NOT NULL,
  outcome_text TEXT NOT NULL,
  excerpt VARCHAR(500) NOT NULL,
  year_label VARCHAR(40) NOT NULL,
  duration_label VARCHAR(120) NOT NULL,
  stack_json JSON NULL,
  highlights_json JSON NULL,
  detail_notes_json JSON NULL,
  links_json JSON NULL,
  image_url VARCHAR(600) NOT NULL,
  image_fit ENUM('cover', 'contain') NOT NULL DEFAULT 'cover',
  is_published TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 100,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_realisation_projects_slug (slug),
  KEY idx_realisation_projects_published (is_published),
  KEY idx_realisation_projects_sort_order (sort_order),
  KEY idx_realisation_projects_tag (tag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
